name: "Run tests"

inputs:
  plugin:
    description: "Name of the plugin to run the tests for"
    required: true

runs:
  using: 'composite'
  steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2

    - name: Install
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install git g++-9 build-essential bison flex \
          libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot \
          pkg-config libboost-system-dev libboost-python-dev \
          libboost-filesystem-dev zlib1g-dev clang-format-8 cmake

    - name: Format
      shell: bash
      run: source .github/workflows/format-check.sh
      env:
        OS: ${{ runner.os }}

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: Install Yosys
      shell: bash
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        source .github/workflows/setup.sh
      env:
        OS: ${{ runner.os }}

    - uses: actions/download-artifact@v3
      if: ${{ inputs.plugin == 'xdc' || inputs.plugin == 'sdc' }}
      with:
        name: design_introspection

    - name: Build and test plugins
      shell: bash
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        source env/conda/bin/activate yosys-plugins
        if [ "$PLUGIN_NAME" = "xdc" ] || [ "$PLUGIN_NAME" = "sdc" ]; then 
          mkdir $CONDA_PREFIX/share/yosys/plugins/
          cp design_introspection.so $CONDA_PREFIX/share/yosys/plugins/
        fi
        source .github/workflows/build-and-test.sh
      env:
        OS: ${{ runner.os }}
        PLUGIN_NAME: ${{ inputs.plugin }}